mercure:
    hubs:
        default:
            url: 'http://localhost:80/.well-known/mercure'
            public_url: 'http://localhost:80/.well-known/mercure'
            jwt:
                secret: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZXJjdXJlIjp7InB1Ymxpc2giOlsiKiJdfX0.yNZvrVvATGXFh6HNp-PD8FYEKkJMtJchsvFYcJEY6go'
                publish: '*'
