<?php

namespace ContainerJsWUbHV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPublication3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.n.7.wCW.App\Entity\Publication' shared service.
     *
     * @return \App\Entity\Publication
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.n.7.wCW": it needs an instance of "App\\Entity\\Publication" but this type has been excluded in "config/services.yaml".');
    }
}
