<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMBF4QUl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMBF4QUl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMBF4QUl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMBF4QUl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMBF4QUl\App_KernelDevDebugContainer([
    'container.build_hash' => 'MBF4QUl',
    'container.build_id' => '17eda36e',
    'container.build_time' => 1699213646,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMBF4QUl');
