<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_book.getAll' => [[], ['_controller' => 'App\\Controller\\BookController::getAll'], [], [['text', '/api/books']], [], [], []],
    'api_get_book' => [['idBook'], ['_controller' => 'App\\Controller\\BookController::getBook'], [], [['variable', '/', '[^/]++', 'idBook', true], ['text', '/api/books']], [], [], []],
    'api_add_book' => [[], ['_controller' => 'App\\Controller\\BookController::addBook'], [], [['text', '/api/books']], [], [], []],
    'api_update_book' => [['idBook'], ['_controller' => 'App\\Controller\\BookController::updateBook'], [], [['variable', '/', '[^/]++', 'idBook', true], ['text', '/api/books']], [], [], []],
    'api_delete_book' => [['id'], ['_controller' => 'App\\Controller\\BookController::deleteBook'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/books']], [], [], []],
    'api_conversations_index' => [['userId'], ['_controller' => 'App\\Controller\\ConversationController::index'], [], [['variable', '/', '[^/]++', 'userId', true], ['text', '/api/conversations/user']], [], [], []],
    'api_conversations_create' => [[], ['_controller' => 'App\\Controller\\ConversationController::create'], [], [['text', '/api/conversations/new']], [], [], []],
    'api_conversations_find.conversation' => [['firstUserId', 'secondUserId'], ['_controller' => 'App\\Controller\\ConversationController::findConversations'], [], [['variable', '/', '[^/]++', 'secondUserId', true], ['variable', '/', '[^/]++', 'firstUserId', true], ['text', '/api/conversations/find']], [], [], []],
    'api_app_dashboard' => [[], ['_controller' => 'App\\Controller\\DashboardController::index'], [], [['text', '/api/dashboard']], [], [], []],
    'api_get.messages' => [['conversationId'], ['_controller' => 'App\\Controller\\MessageController::get'], [], [['variable', '/', '[^/]++', 'conversationId', true], ['text', '/api/messages']], [], [], []],
    'api_create.messages' => [[], ['_controller' => 'App\\Controller\\MessageController::create'], [], [['text', '/api/messages']], [], [], []],
    'api_index' => [[], ['_controller' => 'App\\Controller\\ProjectController::index'], [], [['text', '/api/project']], [], [], []],
    'api_create' => [[], ['_controller' => 'App\\Controller\\ProjectController::create'], [], [['text', '/api/project']], [], [], []],
    'api_show' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/project']], [], [], []],
    'api_delete' => [['id'], ['_controller' => 'App\\Controller\\ProjectController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/project']], [], [], []],
    'api_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::index'], [], [['text', '/api/register']], [], [], []],
    'api_payment' => [[], ['_controller' => 'App\\Controller\\StripeController::makePayment'], [], [['text', '/api/payment']], [], [], []],
    'api_login_check' => [[], [], [], [['text', '/api/login_check']], [], [], []],
];
