<?php

namespace ContainerMBF4QUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EaWM4aRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eaWM4aR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eaWM4aR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'circularReferenceHandler' => ['privates', 'App\\Serializer\\CircularReferenceHandler', 'getCircularReferenceHandlerService', true],
            'conversationRepository' => ['privates', 'App\\Repository\\ConversationRepository', 'getConversationRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'circularReferenceHandler' => 'App\\Serializer\\CircularReferenceHandler',
            'conversationRepository' => 'App\\Repository\\ConversationRepository',
            'serializer' => '?',
        ]);
    }
}
