<?php

namespace ContainerMBF4QUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2PcGlAoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2PcGlAo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2PcGlAo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'book' => ['privates', '.errored..service_locator.2PcGlAo.App\\Entity\\Book', NULL, 'Cannot autowire service ".service_locator.2PcGlAo": it needs an instance of "App\\Entity\\Book" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'book' => 'App\\Entity\\Book',
            'serializer' => '?',
        ]);
    }
}
