<?php

namespace ContainerMBF4QUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IYW9vWfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.iYW9vWf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iYW9vWf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'doctrine' => '?',
            'serializer' => '?',
        ]);
    }
}
