<?php

namespace ContainerMBF4QUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OCnFGBGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.OCnFGBG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.OCnFGBG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'conversation' => ['privates', '.errored..service_locator.OCnFGBG.App\\Entity\\Conversation', NULL, 'Cannot autowire service ".service_locator.OCnFGBG": it needs an instance of "App\\Entity\\Conversation" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'conversation' => 'App\\Entity\\Conversation',
            'serializer' => '?',
        ]);
    }
}
