<?php

namespace ContainerMBF4QUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LWeIwFrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LWeIwFr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LWeIwFr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'publication' => ['privates', '.errored..service_locator.LWeIwFr.App\\Entity\\Publication', NULL, 'Cannot autowire service ".service_locator.LWeIwFr": it needs an instance of "App\\Entity\\Publication" but this type has been excluded in "config/services.yaml".'],
            'publicationRepository' => ['privates', 'App\\Repository\\PublicationRepository', 'getPublicationRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'entityManager' => '?',
            'publication' => 'App\\Entity\\Publication',
            'publicationRepository' => 'App\\Repository\\PublicationRepository',
            'serializer' => '?',
        ]);
    }
}
