<?php

namespace ContainerMBF4QUl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCircularReferenceHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Serializer\CircularReferenceHandler' shared autowired service.
     *
     * @return \App\Serializer\CircularReferenceHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Serializer/CircularReferenceHandler.php';

        return $container->privates['App\\Serializer\\CircularReferenceHandler'] = new \App\Serializer\CircularReferenceHandler();
    }
}
